sudo: false
language: php

php:
  - 7.0

env:
  - TERMINUS_ENV=$TRAVIS_BUILD_ID

addons:
  ssh_known_hosts:
   - codeserver.dev.84245a58-c1ac-48c0-8e01-6b5a34623df1.drush.in:2222

before_install:
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - composer global require -n "hirak/prestissimo:^0.3"
  - composer global require -n "consolidation/cgr"
  - cgr "pantheon-systems/terminus:^1"
  - terminus --version
  - mkdir -p $HOME/.terminus/plugins
  - composer create-project -n -d $HOME/.terminus/plugins pantheon-systems/terminus-build-tools-plugin:^1
  - composer create-project -n -d $HOME/.terminus/plugins pantheon-systems/terminus-secrets-plugin:^1
  - git config --global user.email "admin@test.com"
  - git config --global user.name "Travis CI"

before_script:
  - terminus auth:login -n --machine-token="$TERMINUS_TOKEN"
  - terminus build-env:delete:ci -n "$TERMINUS_SITE" --keep=2 --yes
  - terminus env:wake -n "$TERMINUS_SITE.dev"
  - |
      if [[ $TRAVIS_PULL_REQUEST != false ]] ; then
        terminus build-env:create -n "$TERMINUS_SITE.dev" "$TERMINUS_ENV" --yes --clone-content
      fi

script:
  - "Hooray~|!"
