sudo: false
language: php

php:
  - 7.0

env:
  - TERMINUS_ENV=$TRAVIS_BUILD_ID

addons:
  ssh_known_hosts:
   - ssh://codeserver.dev.84245a58-c1ac-48c0-8e01-6b5a34623df1@codeserver.dev.84245a58-c1ac-48c0-8e01-6b5a34623df1.drush.in:2222

before_install:
  - export PATH="$HOME/.config/composer/vendor/bin:$PATH"
  - composer global require -n "hirak/prestissimo:^0.3"
  - composer global require -n "consolidation/cgr"
  - cgr "pantheon-systems/terminus:^1"
  - terminus --version
  - cgr "drush/drush:~8"
  - mkdir -p $TRAVIS_BUILD_DIR/terminus/plugins
  - composer create-project -n -d ~/.terminus/plugins pantheon-systems/terminus-build-tools-plugin:^1
  - composer create-project -n -d ~/.terminus/plugins pantheon-systems/terminus-secrets-plugin:^1

before_script:
  - terminus build-env:delete:ci -n "$TERMINUS_SITE" --keep=2 --yes
  - composer -n build-assets
  - terminus env:wake -n "$TERMINUS_SITE.dev"
  - terminus build-env:create -n "$TERMINUS_SITE.dev" "$TERMINUS_ENV" --yes --clone-content
